apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-lab-web
  namespace: docker-lab
  labels:
    app.kubernetes.io/name: docker-lab
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: docker-lab
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: docker-lab
        app.kubernetes.io/component: web
    spec:
      containers:
        - name: web
          image: ghcr.io/s8kevinaf02/docker-lab:52a0bdffe49be6fffebe77d41cd9150d54b25dc
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: APP_ENV
              value: "dev"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 128Mi
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
            runAsGroup: 101
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory