apiVersion: v1
kind: Service
metadata:
  name: docker-lab-web
  namespace: docker-lab
  labels:
    app.kubernetes.io/name: docker-lab
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: docker-lab
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: 80
      targetPort: http